<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Ammu8867" failures="1" tests="4" name="AmazonMavenPOM_Test.Amazon_TC08" time="161.178" errors="0" timestamp="2024-03-19T12:58:37 IST" skipped="3">
  <testcase classname="AmazonMavenPOM_Test.Amazon_TC08" name="SortProduct" time="30.844">
    <failure message="expected [Newest Arrivals] but found [3]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Newest Arrivals] but found [3]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at AmazonMavenPOM_Pages.Amz_ProductSortPageTC08.SortBY_Newest_Arrivals(Amz_ProductSortPageTC08.java:34)
at AmazonMavenPOM_Test.Amazon_TC08.SortProduct(Amazon_TC08.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
    <system-out>
      <![CDATA[Test Case Failed while execution hence takeing Sceenshoot]]>
    </system-out>
  </testcase> <!-- SortProduct -->
  <testcase classname="AmazonMavenPOM_Test.Amazon_TC08" name="SortProduct" time="49.527">
    <skipped/>
  </testcase> <!-- SortProduct -->
  <testcase classname="AmazonMavenPOM_Test.Amazon_TC08" name="SortProduct" time="40.538">
    <skipped/>
  </testcase> <!-- SortProduct -->
  <testcase classname="AmazonMavenPOM_Test.Amazon_TC08" name="SortProduct" time="40.269">
    <skipped/>
  </testcase> <!-- SortProduct -->
  <system-out>
    <![CDATA[Test Case Failed while execution hence takeing Sceenshoot
Test Case Success while execution hence takeing Sceenshoot
Test Case Failed while execution hence takeing Sceenshoot
Test Case Success while execution hence takeing Sceenshoot
Test Case Success while execution hence takeing Sceenshoot
Test Case Success while execution hence takeing Sceenshoot
Test Case Failed while execution hence takeing Sceenshoot
Test Case Success while execution hence takeing Sceenshoot
Test Case Success while execution hence takeing Sceenshoot
Test Case Success while execution hence takeing Sceenshoot
Test Case Failed while execution hence takeing Sceenshoot]]>
  </system-out>
</testsuite> <!-- AmazonMavenPOM_Test.Amazon_TC08 -->
